name: parade
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - cuda-toolkit
  - pytorch-cuda
  - python>=3.11
  - biopython>=1.81
  - ipykernel>=6.23.1
  - ipython
  - matplotlib>=3.7.1
  - numpy>=1.24.3
  - pandas>=2.0.2
  - pyarrow>=12.0.0
  - pygad>=3.1.0
  - pytorch=>2.0.1
  - pytorch-lightning>=2.0
  - scikit-learn>=1.2.2
  - scipy>=1.13.0
  - seaborn>=0.13.2
  - tqdm
  - umap-learn>=0.5.5
  - yaml>=0.2.5